# Generated by Django 3.1.6 on 2021-02-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0004_auto_20210211_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
